included: 
  # View
  - ../GBHFacebookImagePicker/Classes/View 

  # Controller 
  - ../GBHFacebookImagePicker/Classes/Controller

  # Model 
  - ../GBHFacebookImagePicker/Classes/Model

disabled_rules:
  - multiple_closures_with_trailing_closure

line_length: 150