platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'GBHFacebookImagePicker_Example' do
  pod 'GBHFacebookImagePicker', :path => '../'

  target 'GBHFacebookImagePicker_Tests' do
    inherit! :search_paths
  end
end
